config/routes.rb
# frozen_string_literal: true

Cricdata::Application.routes.draw do
  root to: 'static#api'

  resources :players

  scope ':match_type_name', constraints: { match_type_name: /test|odi|t20i/ } do
    resources :players, only: [:show] do
      get 'xfactor', on: :collection
    end

    scope '/scores' do
      resources :individual,  controller: :individual_scores
      resources :team,        controller: :team_scores
    end
  end

  get ':action' => 'static#:action'
end

app/models/individual_score.rb
# frozen_string_literal: true

class IndividualScore
  include Mongoid::Document

  # Fields
  field :type_number,               type: Integer
  field :runs,                      type: Integer
  field :date_start,                type: Date
  field :name,                      type: String
  field :latest_date,               type: Date
  field :latest_name,               type: String
  field :latest_player_id,          type: String
  field :unscored,                  type: Boolean
  field :current_lowest_unscored,   type: Boolean
  field :has_been_lowest_unscored,  type: Boolean
  field :has_been_highest_score,    type: Boolean
  field :frequency,                 type: Integer
  field :notouts,                   type: Integer

  #  key :type_number, :runs

  # Indexes
  index({ type_number: 1, runs: 1 }, { unique: true })

  # Relationships
  belongs_to :player
  belongs_to :inning

  # Scopes
  default_scope -> { asc(:type_number).desc(:runs) }

  # Helpers
  # Register an individual score
  def self.register(inning, match_type_player, runs, date_start, notout)
    type_number = match_type_player.type_number
    score_max   = where(type_number: type_number).asc(:runs).last

    if score_max.blank?
      # Seed the collection
      score_max                           = find_or_create_by type_number: type_number, runs: 0
      score_max.unscored                  = true
      score_max.current_lowest_unscored   = true
      score_max.has_been_lowest_unscored  = true
      score_max.save
    end

    max_runs = score_max.runs
    # -dputs inning, :cyan # debug
    # -dprint runs, :cyan # debug
    # -dprint max_runs, :cyan # debug

    if runs > max_runs
      # Fill in any gaps
      while runs > max_runs
        max_runs += 1
        score = find_or_create_by type_number: type_number, runs: max_runs

        if score.unscored.blank?
          score.unscored = true
          score.save
        end
        # -dprint max_runs, :pink # debug
      end

      score.has_been_highest_score = true
      score.save
    end
    # -dputs ' ' # debug

    score           = find_or_create_by type_number: type_number, runs: runs
    score.unscored  = false # that's a given

    # Update counts
    score.frequency = score.frequency.blank? ? 1 : score.frequency + 1
    score.notouts   = (score.notouts.blank? ? 1 : score.notouts + 1) if notout

    # Is this an earlier (or the first) performance?
    if score.date_start.blank? || (date_start < score.date_start)
      score.inning      = inning
      score.player      = match_type_player.player
      score.name        = match_type_player.name
      score.date_start  = date_start
    end

    # -dp match_type_player, :pink # debug

    # Is this a later (or the last) performance?
    if score.latest_date.blank? || (date_start > score.latest_date)
      score.latest_name       = match_type_player.name
      score.latest_date       = date_start
      score.latest_player_id  = match_type_player.player._id
    end

    # Is this the current lowest unscored score?
    if score.current_lowest_unscored == true
      score.current_lowest_unscored = false
      score.save

      # Now look for the next lowest
      lu = where(type_number: type_number, unscored: true).asc(:runs).first

      if lu.blank? # All scores might have been scored
        # Add a score 1 higher than the current highest score
        lu_runs = where(type_number: type_number).max(:runs) + 1
        lu_runs = runs + 1 if lu_runs.blank?
        lu      = find_or_create_by type_number: type_number, runs: lu_runs
      end

      lu.unscored                  = true
      lu.current_lowest_unscored   = true
      lu.has_been_lowest_unscored  = true
      lu.save
      # -dp lu # debug
    end

    # Save it
    score.save
    # -dp score # debug
  end
end

app/controllers/individual_scores_controller.rb
# frozen_string_literal: true

class IndividualScoresController < ApplicationController
  include ConsoleLog

  before_action :parse_match_type

  def parse_match_type
    permitted = params.permit(:match_type_name)
    match_type = MatchType.from_slug(permitted[:match_type_name])

    if match_type
      @type_number = match_type.type_number
    else
      respond_to do |format|
        format.html { render 'match_types/unrecognised' }
      end
    end
  end

  # GET /:match_type_name/scores/individual
  # GET /:match_type_name/scores/individual.json
  def index
    @individual_scores = IndividualScore.where(type_number: @type_number).all

    @rubric = {}

    case @type_number
    when MatchType::TEST
      @rubric = {
        title: 'test matches',
        clarification: 'Individual scores in test matches'
      }
    when MatchType::ODI
      @rubric = {
        title: 'one-day internationals',
        clarification: 'Individual scores in one-day internationals'
      }
    when MatchType::T20I
      @rubric = {
        title: 'Twenty20 internationals',
        clarification: 'Individual scores in Twenty20 internationals'
      }
    end

    @rubric[:match_type_name] = params[:match_type_name]
    dputs params
    dputs @rubric

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @individual_scores }
    end
  end

  # GET /:match_type_name/scores/individual/1
  # GET /:match_type_name/scores/individual/1.json
  def show
    @performances = Performance.batting.where(type_number: @type_number, runs: params[:id]).asc :date_start

    @rubric = {}

    case @type_number
    when MatchType::TEST
      @rubric = {
        title: 'test matches',
        clarification: 'The history of a particular score in test matches'
      }
    when MatchType::ODI
      @rubric = {
        title: 'one-day internationals',
        clarification: 'The history of a particular score in one-day internationals'
      }
    when MatchType::T20I
      @rubric = {
        title: 'Twenty20 internationals',
        clarification: 'The history of a particular score in Twenty20 internationals'
      }
    end

    @rubric[:match_type_name] = params[:match_type_name]
    dputs params
    dputs @rubric

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @performances }
    end
  end
end

app/helpers/individual_scores_helper.rb
# frozen_string_literal: true

module IndividualScoresHelper
end

app/views/individual_scores/index.html.erb
<h1>Individual scores - <%= @rubric[:title] %></h1>

<table class="scores">
  <caption>
    <p><%= @rubric[:clarification] %></p>
    <p>Key:</p>
    <p class="highest">Has been highest score &#10003;</p>
    <p class="lowest">Has been lowest unscored score &#10003;</p>
  </caption>

  <tr>
    <th class="score">Score</th>
    <th>Lowest</th>
    <th>Highest</th>
    <th>Frequency</th>
    <th>Not outs</th>
    <th>First scored</th>
    <th>By</th>
    <th>Last scored</th>
    <th>By</th>
  </tr>

  <%
  @individual_scores.each do |score|
    td_class = score.unscored ? 'unscored' : 'scored'
    td_class += ' lowest'	if score.has_been_lowest_unscored
    td_class += ' highest'	if score.has_been_highest_score
    td_class += ' unscored'	if score.unscored
  %>
  <tr class="<%= td_class %>">
    <% if score.unscored %>
	<td class="score <%= td_class %>"><%= score.runs %></td>
	<td class="<%= td_class %>" colspan="8">Current lowest unscored score</td>
    <% else %>
	<td class="score <%= td_class %>"><%= link_to score.runs, individual_path(@rubric[:match_type_name], score.runs), :class => td_class %></td>
	<td class="<%= td_class %>"><%=raw score.has_been_lowest_unscored ? '&#10003;' : '' %></td>
	<td class="<%= td_class %>"><%=raw score.has_been_highest_score ? '&#10003;' : '' %></td>
	<td class="<%= td_class %>"><%= score.frequency %></td>
	<td class="<%= td_class %>"><%= score.notouts %></td>
	<td class="<%= td_class %>"><%= score.date_start %></td>
	<td class="<%= td_class %>"><a href="<%= '/players/' + (score.player_id.blank? ? '' : score.player_id) %>"><%= score.name %></a></td>
	<td class="<%= td_class %>"><%= score.latest_date %></td>
	<td class="<%= td_class %>"><a href="<%= '/players/' + (score.latest_player_id.blank? ? '' : score.latest_player_id) %>"><%= score.latest_name %></a></td>
    <% end %>
  </tr>
  <% end %>
</table>

app/views/individual_scores/show.html.erb
<h1>Individual scores - <%= @rubric[:title] %> - <%= params[:id] %></h1>

<table class="performances">
  <caption>
    <p><%= @rubric[:clarification] %></p>
  </caption>

  <tr>
    <th>Match start date</th>
    <th>By</th>
  </tr>

  <% @performances.each do |pf| %>
  <tr>
	<td><%= pf.date_start %></td>
	<td>
		<% # link_to pf.name, pf.match_type_player.player %>
		<a href="/players/<%= pf.player_id %>"><%= pf.name %></a>
	</td>
  </tr>
  <% end %>
</table>